config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  namespace :admin do
    resources :categories do
      resources :words 
    end
  end

  resources :lessons do
    resources :answers
  end

  resources :categories, only: [:index]
  resources :words, only: [:index]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    begin
      user = User.find(current_user.id)
      @activities = Activity.where("user_id IN (?) OR user_id = ?", user.following_ids, user.id).paginate(page: params[:page], per_page:10)
    rescue 
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

  def full_title(page_title = '')
    base_title = "E-Learning App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<% if logged_in? %>
<br>
<div class="container">
    <div class="row">
        <div class="col s4">
            <div class="card">
                <div class="card-action light-blue darken-2 white-text">
                    <h6>User Information</h6>
                </div>
                <div style="text-align:center;">
                    <div class="card-image">
                        <%= gravatar_for current_user %>
                    </div>
                    <div class="card-content">
                        <h3><%= current_user.name %></h3>
                        <h4><%= current_user.email %></h4>
                    </div>        
                </div>
            </div>
            <div class="card">
                <div class="card-action light-blue darken-2 white-text">
                    <h6>User Status</h6>
                </div>
                <div class="card-content" style="text-align:center;"> 
                    <% total = current_user.answers.count %> 
                    <h4><b><%= link_to "Words Learned: #{total}", words_path %></b></h4>
                    <div class = "status">
                        <%= render 'shared/stats' %>
                    </div>
                </div>
            </div>

            <div class="card">
                <div class="card-action light-blue darken-2 white-text">
                    <h6>Calendar </h6>
                </div>
                <br>
                <iframe src="https://calendar.google.com/calendar/embed?height=410&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=Asia%2FManila&amp;src=bWFwYWpvaG5lZGVsQGdtYWlsLmNvbQ&amp;src=ZWg4cmY4ZWsyaDdwZWYzNzFvY21udG44MzhAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;src=ZW4uY2hyaXN0aWFuI2hvbGlkYXlAZ3JvdXAudi5jYWxlbmRhci5nb29nbGUuY29t&amp;src=Y2xhc3Nyb29tMTA4MDI1NjcwOTEwOTM0MzM2NzIzQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20&amp;src=ZW4ucGhpbGlwcGluZXMjaG9saWRheUBncm91cC52LmNhbGVuZGFyLmdvb2dsZS5jb20&amp;color=%237986CB&amp;color=%23F4511E&amp;color=%230B8043&amp;color=%23263238&amp;color=%230B8043&amp;showTitle=0&amp;showPrint=0&amp;showNav=1&amp;showTabs=0&amp;showCalendars=0&amp;showTz=1" style="border-width:0" width="293" height="315" frameborder="0" scrolling="no"></iframe>
            </div>
        </div>
        <div class="col s8">
            <div class="card">
                <div class="card-action light-blue darken-2 white-text"><h6> Activity Feed </h6></div>
                <ul class="collection">
                    <%= render 'activity/feed'%>
                </ul>
                <%= will_paginate @activities %>
            </div>
        </div>
    </div>
</div>
<% else %>
<div class="section no-pad-bot" id="index-banner">
    <div class="container">
        <br><br>
        <h1 class="header center">E-Learning System</h1>
        <div class="row center">
            <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
        </div>
        <div class="row center">
            <%= link_to "Get Started", signup_path, class: "btn-large waves-effect waves-light", id:"download-button" %>
        </div>
        <br><br>
    </div>
</div>
<% end %>