config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  namespace :admin do
    resources :categories do
      resources :words 
    end
  end

  resources :lessons do
    resources :answers
  end

  resources :categories, only: [:index]
  resources :words, only: [:index]
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :choices, dependent: :destroy
  accepts_nested_attributes_for :choices, allow_destroy: true,  reject_if: :all_blank
  validates :content, length: { maximum: 50 }
  validates_presence_of :content, message: "word can't be blank"
  default_scope -> { order(created_at: :desc) }
  validate :one_choice_only
  validate :must_unique
  has_many :answers, dependent: :destroy
  has_many :lessons, through: :answers  
 
  def correct_ans
    choices.find_by(correct: true).try(:content)
  end

  def one_choice_only
    answer = choices.collect { |choice| choice.correct}.count(true)
    unless answer == 1
      return errors.add(:base, "Please check only one correct answer")
    end
  end

  def must_unique
    uniqLength = choices.uniq { |choice| choice.content.downcase }.count
    if uniqLength < choices.length
      return errors.add(:base, "Duplication of choices, it must be unique")
    end
  end
end

app/controllers/admin/words_controller.rb
module Admin 
  class WordsController < ApplicationController

    before_action :logged_in_user
    before_action :admin_user

    def index
      @category = Category.find(params[:category_id])
      @words = @category.words.paginate(page: params[:page])
    end

    def show
    end

    def new
      @category = Category.find(params[:category_id])
      @word = @category.words.build
      3.times { @word.choices.build }
    end
  
    def create
      @category = Category.find(params[:category_id])
      @word = @category.words.build(word_params)
      if @word.save
        flash[:success] = "Word successfully created!"
        redirect_to admin_category_words_url
      else
        render 'new'
      end
    end

    def edit
      @word = Word.find(params[:id])
      @category = Category.find(params[:category_id])
    end

    def update
      @category = Category.find(params[:category_id])
      @word = Word.find(params[:id])
        if @word.update_attributes(word_params)
          flash[:success] = "Word Successfully Updated!"
          redirect_to admin_category_words_url
        else
          render 'edit'
        end
    end

    def destroy
      Word.find(params[:id]).destroy
      flash[:success] = "Word Deleted"
      redirect_to admin_category_words_url
    end
    
    private
    def word_params
      params.require(:word).permit(:content, choices_attributes: [:id, :content, :correct])
    end
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  before_action :logged_in_user
  
  def index
    @user = User.find(current_user.id)
    @answers = @user.answers
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/admin/words/_form.html.erb
<%= form_for([:admin, @category, @word]) do |f| %>
    <%= render 'shared/error_messages', object: @word %>
    <div class="form-field">
        <%= f.label :content, "Word" %>
        <%= f.text_field :content %>    
    </div>
    <div class="form-field">
        <%= f.label "Choices" %>
        <%= f.fields_for :choices do |choice| %>
            <%= choice.text_field :content %>
            <%= choice.label :correct, class: "checkbox inline" do %>
                <%= choice.check_box :correct %>
                <span>Correct</span>
            <% end %>
        <% end %>
    </div> 
    <br>
    <div class="form-field">
        <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    </div>
<% end %>

app/views/admin/words/create.html.erb
<h1>Words#create</h1>
<p>Find me in app/views/words/create.html.erb</p>

app/views/admin/words/edit.html.erb
<% provide(:title, 'Edit Word') %>
<% provide(:button_text, 'Edit Word') %>
<div class="container"><br>
    <div class="card">
        <div class="card-action light-blue darken-2 white-text">
            <h6>Admin | <%= @category.title %> - Words</h6>
        </div>
        <div class="form-padding">  
            <%= link_to "Back", admin_category_words_path , class: 'btn green lighten-1' %> <br><br>
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/admin/words/index.html.erb
<% provide(:title, "All Words")%>
<div class=container>
    <div class=row>
        <h3><%= @category.title %></h3>
        <h5><%= @category.description %></h5>
        <%= link_to "Back", admin_categories_path , class: 'btn green lighten-1' %>
        <%= link_to "Add Word", new_admin_category_word_path , class: 'btn btn-primary' %>
        <%= will_paginate %>
        <table>
            <thead>
                <tr>
                    <th>Word</th>
                    <th>Answer</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <% @words.each do |word| %>
                <tr>
                    <td><%= word.content %></td>
                    <td><%= word.correct_ans %></td>
                    <td>
                    <%= link_to "Edit", edit_admin_category_word_path(@category, word), 
                    class: 'btn blue lighten-1' %> 
                    <%= link_to "Delete", [:admin, @category, word], method: :delete, 
                    data: {confirm: "Are you sure you want to delete this category?"},
                    class: 'btn red darken-1' %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
        <%= will_paginate %>
    </div>
</div>

app/views/admin/words/new.html.erb
<% provide(:title, 'Add Word') %>
<% provide(:button_text, 'Save Word') %>
<div class="container"><br>
    <div class="card">
        <div class="card-action light-blue darken-2 white-text">
            <h6>Add Word</h6>
        </div>
        <div class="form-padding">
            <%= link_to "Back", admin_category_words_path , class: 'btn green lighten-1' %> <br><br>
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/admin/words/show.html.erb
<h1>Words#show</h1>
<p>Find me in app/views/words/show.html.erb</p>

app/views/admin/words/update.html.erb
<h1>Words#update</h1>
<p>Find me in app/views/words/update.html.erb</p>