config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  namespace :admin do
    resources :categories do
      resources :words 
    end
  end

  resources :lessons do
    resources :answers
  end

  resources :categories, only: [:index]
  resources :words, only: [:index]
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  validates :title, presence: true, length: { maximum: 50 }
  validates :description,  presence: true, length: { maximum: 150 }
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy

end

app/controllers/admin/categories_controller.rb
module Admin 
  class CategoriesController < ApplicationController

    before_action :logged_in_user
    before_action :admin_user

    def index
      @categories = Category.paginate(page: params[:page])
    end

    def show
      @category = Category.find(params[:id])
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        flash[:success] = "Category Successfully Created!"
        redirect_to admin_categories_url
      else
        render 'new'
      end
    end

    def edit
      @category = Category.find(params[:id])
    end

    def update
      @category = Category.find(params[:id])
      if @category.update_attributes(category_params)
        flash[:success] = "Category Successfully Updated!"
        redirect_to admin_categories_url
      else
        render 'edit'
      end
    end

    def destroy
      Category.find(params[:id]).destroy
      flash[:success] = "Category Deleted"
      redirect_to admin_categories_url
    end

    private
      def category_params
        params.require(:category).permit(:title, :description)
      end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :logged_in_user

  def index
    @categories = Category.paginate(page: params[:page], per_page:10)
    @lesson = Lesson.new
    @user = User.find(current_user.id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, @category]) do |f| %>
    <%= render 'shared/error_messages', object: @category %>
    <div class="form-field">
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div class="form-field">
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>
    <br>
    <div class="form-field">
        <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    </div>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide(:title, 'Update Category') %>
<% provide(:button_text, 'Update Category') %>
<div class="container"><br>
    <div class="card">
        <div class="card-action light-blue darken-2 white-text">
            <h6>Update Category</h6>
        </div>
        <div class="form-padding">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/admin/categories/index.html.erb
<% provide(:title, "All Categories")%>
<div class=container>
    <div class=row>
        <h1> All Categories </h1>
        <%= link_to "Add Category", new_admin_category_path, class: 'btn btn-primary' %>
        <%= will_paginate %>
        <table>
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Words</th>
                    <th>Action</th>
                </tr>
            </thead>

            <tbody>
                <% @categories.each do |category| %>
                <tr>
                    <td><%= category.title %></td>
                    <td><%= category.description %></td>
                    <td><%= category.words.count %></td>
                    <td>
                    <%= link_to "Add Word", admin_category_words_path(category), 
                    class: 'btn btn-primary' %> 
                    <%= link_to "Edit", edit_admin_category_path(category), 
                    class: 'btn blue lighten-1' %> 
                    <%= link_to "Delete", [:admin, category], method: :delete, 
                    data: {confirm: "Are you sure you want to delete this category?"},
                    class: 'btn red darken-1' %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
        <%= will_paginate %>
    </div>
</div>

app/views/admin/categories/new.html.erb
<% provide(:title, 'Add Category') %>
<% provide(:button_text, 'Save Category') %>
<div class="container"><br>
    <div class="card">
        <div class="card-action light-blue darken-2 white-text">
            <h6>Add Category</h6>
        </div>
        <div class="form-padding">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/admin/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>