config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  namespace :admin do
    resources :categories do
      resources :words 
    end
  end

  resources :lessons do
    resources :answers
  end

  resources :categories, only: [:index]
  resources :words, only: [:index]
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  validates :title, presence: true, length: { maximum: 50 }
  validates :description,  presence: true, length: { maximum: 150 }
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy

end

app/controllers/admin/categories_controller.rb
module Admin 
  class CategoriesController < ApplicationController

    before_action :logged_in_user
    before_action :admin_user

    def index
      @categories = Category.paginate(page: params[:page])
    end

    def show
      @category = Category.find(params[:id])
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        flash[:success] = "Category Successfully Created!"
        redirect_to admin_categories_url
      else
        render 'new'
      end
    end

    def edit
      @category = Category.find(params[:id])
    end

    def update
      @category = Category.find(params[:id])
      if @category.update_attributes(category_params)
        flash[:success] = "Category Successfully Updated!"
        redirect_to admin_categories_url
      else
        render 'edit'
      end
    end

    def destroy
      Category.find(params[:id]).destroy
      flash[:success] = "Category Deleted"
      redirect_to admin_categories_url
    end

    private
      def category_params
        params.require(:category).permit(:title, :description)
      end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :logged_in_user

  def index
    @categories = Category.paginate(page: params[:page], per_page:10)
    @lesson = Lesson.new
    @user = User.find(current_user.id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<% provide(:title, 'Update Category') %>
<% provide(:button_text, 'Update Category') %>
<div class="container"><br>
    <div class="card">
        <div class="card-action red lighten-2 white-text">
            <h6>Update Category</h6>
        </div>
        <div class="form-padding">
            <%= render 'categories/form' %>
        </div>
    </div>
</div>

app/views/categories/index.html.erb
<% provide(:title, "Categories") %>
<br>
<div class="container">
    <div class="row">
        <div class="col s12">
            <div class="card">
                <div class="card-action light-blue darken-2 white-text">
                    <h6>All Categories</h6>
                </div>
                <% unless @categories.blank? %>
                    <%= will_paginate %>
                    <div class=row>
                        <% @categories.each do |category| %>
                            <% if category.words.any? %>
                                <% lesson = @user.lesson_taken(category.id) %>
                                <div class="col s12 m6">
                                    <div class="card-content">
                                        <div class="something">
                                            <div class="card blue-grey darken-0">
                                                <div class="card-content white-text">
                                                    <span class="card-title">
                                                        <% if lesson.nil? %>
                                                            <h6><%= category.title %> </h6>
                                                        <% else %>
                                                            <span class="new badge" data-badge-caption=""><%= lesson.score %> / <%= lesson.category.words.count %></span>
                                                            <h6><%= category.title %></h6>
                                                        <% end %> 
                                                    </span>
                                                    <p> <b>[ <%= category.words.count %> words ] </b> <%= category.description %>
                                                    </p>
                                                </div>    
                                                <% if lesson.nil? %>       
                                                    <div class="card-action">
                                                        <%= link_to "Start Lesson", lessons_path(category_id: category.id), method: :post, class: 'btn btn-primary' %>
                                                    </div>
                                                <% else %>
                                                    <% if lesson.score.nil?%>
                                                        <div class="card-action">
                                                            <%= link_to "Continue Lesson", new_lesson_answer_path(lesson), class: 'btn orange darken-2' %> 
                                                        </div>
                                                    <% else %>
                                                        <div class="card-action">
                                                            <%= link_to "See Result", lesson, class: 'btn grey darken-1' %> 
                                                        </div>
                                                    <% end %>
                                                <% end %>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <% end %>
                        <% end %>
                    </div>
                    <%= will_paginate %>
                <% else %>
                    <ul class="collection">
                        <li class="collection-item">
                            <h6> No categories. </h6>
                        </li>
                    <ul>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/categories/new.html.erb
<% provide(:title, 'Add Category') %>
<% provide(:button_text, 'Save Category') %>
<div class="container"><br>
    <div class="card">
        <div class="card-action red lighten-2 white-text">
            <h6>Add Category</h6>
        </div>
        <div class="form-padding">
            <%= render 'categories/form' %>
        </div>
    </div>
</div>